config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  root to: "public#index"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community
  belongs_to :account
  validates_presence_of :url, :name, :bio
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_authentication :authenticate_account!, except: [ :index, :show]

  def index
    @communities = Community.all
  end

  def show
  end

  def new
  end

  def create
  end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
footer

app/views/layouts/_header.html.erb
<div class="container"> 
  <div class="row">
    <div class="col-12 pt-3 mb-4 border-bottom">
      <div class="float-right">
        <% if account_signed_in? %>
          <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "btn btn-primary"%>
        <% else %>
        <%= link_to "Log In", new_account_session_path, class: "btn btn-outline-primary"%>
        <%= link_to "Sing Up", new_account_registration_path, class: "btn btn-primary"%>
        <% end %>
      </div>
      <p class="h3">Reddit Clone</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit Clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
  
    <%= yield %>

    <%= render partial: "layouts/footer" %>

  </body>
</html>